version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    ports:
    - "8080:8080"
    restart: always
  sonarqube:
    image: sonarqube:latest
    ports:
    - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
